Repository daeuniverse/daed, pull requests merged in 2023-07, with the labels that each got.

#124 fix: try fixing caret misplacement
  src/components/PlainTextFormModal.tsx
  src/constants/editor.ts
  src/constants/index.ts
  src/main.tsx
  src/pages/Experiment.tsx
Labels: fix, not-yet-tested

#125 feat: add a configure node modal
  .eslintrc.yml
  package.json
  pnpm-lock.yaml
  src/apis/mutation.ts
  src/components/ConfigureNodeFormModal/HTTPForm.tsx
  src/components/ConfigureNodeFormModal/SSForm.tsx
  src/components/ConfigureNodeFormModal/SSRForm.tsx
  src/components/ConfigureNodeFormModal/Socks5Form.tsx
  src/components/ConfigureNodeFormModal/TrojanForm.tsx
  src/components/ConfigureNodeFormModal/V2rayForm.tsx
  src/components/ConfigureNodeFormModal/index.tsx
  src/components/CreateNodeFormModal.tsx
  src/components/DraggableResourceBadge.tsx
  src/components/GroupFormModal.tsx
  src/components/Header.tsx
  src/components/PlainTextFormModal.tsx
  src/components/index.ts
  src/constants/default.ts
  src/constants/index.ts
  src/constants/misc.ts
  src/constants/schema.ts
  src/i18n/locales/en.json
  src/i18n/locales/zh-Hans.json
  src/pages/Experiment.tsx
  src/pages/Orchestrate/Config.tsx
  src/pages/Orchestrate/DNS.tsx
  src/pages/Orchestrate/Group.tsx
  src/pages/Orchestrate/Node.tsx
  src/pages/Orchestrate/Routing.tsx
  src/pages/Orchestrate/index.tsx
  src/utils/helper.ts
  src/utils/index.ts
  src/utils/node.ts
Labels: feature, not-yet-tested

#133 feat: wan interface auto detect
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/apis/mutation.ts
  src/apis/query.ts
  src/components/ConfigFormModal.tsx
  src/components/ConfigureNodeFormModal/SSRForm.tsx
  src/components/ConfigureNodeFormModal/TrojanForm.tsx
  src/components/ConfigureNodeFormModal/V2rayForm.tsx
  src/components/ConfigureNodeFormModal/index.tsx
  src/components/Header.tsx
  src/components/ImportResourceFormModal.tsx
  src/components/PlainTextFormModal.tsx
  src/components/RenameFormModal.tsx
  src/components/SelectItemWithDescription.tsx
  src/components/SimpleCard.tsx
  src/constants/default.ts
  src/contexts/index.tsx
  src/i18n/locales/en.json
  src/i18n/locales/zh-Hans.json
  src/initialize.ts
  src/pages/Experiment.tsx
  src/pages/MainLayout.tsx
  src/pages/Orchestrate/Config.tsx
  src/pages/Orchestrate/DNS.tsx
  src/pages/Orchestrate/Group.tsx
  src/pages/Orchestrate/Routing.tsx
  src/pages/Orchestrate/index.tsx
  src/pages/Setup.tsx
  src/schemas/gql/fragment-masking.ts
  src/schemas/gql/gql.ts
  src/store/index.ts
Labels: feature, not-yet-tested

#136 docs(readme): add release badge
  README.md
Labels: documentation

#138 ci: refine pr-build workflow
  .github/workflows/build.yml
  .github/workflows/pr-build.yml
  docs/getting-started.md
Labels: ci, tested

#144 release: draft release for v0.1.1
  CHANGELOGS.md
Labels: chore, release:auto

#147 feat: change icons
  src/components/Section.tsx
  src/components/SimpleCard.tsx
  src/components/UpdateSubscriptionAction.tsx
  src/pages/Orchestrate/Node.tsx
  src/pages/Orchestrate/Subscription.tsx
Labels: feature, not-yet-tested

#137 ci(build): publish `ghcr.io` docker image
  .github/workflows/publish-docker-image.yml
  Dockerfile
  src/components/Header.tsx
  src/vite-env.d.ts
  vite.config.ts
Labels: ci

#148 chore(pr_template): add test result section
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#146 ci(generate-changelogs): set dry_run to true by default
  .github/workflows/generate-changelogs.yml
Labels: ci, tested

#152 ci(sync-upstream): fix invalid downstream workflow ref
  .github/workflows/sync-upstream.yml
Labels: ci

#149 feat: modal reworks
  .lintstagedrc.yml
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/QRCodeModal.tsx
  src/constants/editor.ts
  src/main.tsx
Labels: feature, not-yet-tested

#156 fix: wan interface should be optional
  src/components/ConfigFormModal.tsx
Labels: fix, not-yet-tested

#158 ci(build): rename Build (Stable) -> Build (Main)
  .github/workflows/build.yml
Labels: ci, not-yet-tested

#159 fix(v2ray): add missing websocket path field
  src/components/ConfigureNodeFormModal/TuicForm.tsx
  src/components/ConfigureNodeFormModal/V2rayForm.tsx
  src/i18n/locales/en.json
  src/i18n/locales/zh-Hans.json
Labels: fix, not-yet-tested

#162 ci(pr-build): integrate check runs to report build status
  .github/workflows/pr-build.yml
Labels: ci, tested

#163 ci/chore(pr-build): remove unnecessary lines
  .github/workflows/pr-build.yml
Labels: ci, chore

#169 chore: update packages
  .github/workflows/pr-build.yml
  .prettierrc
  CHANGELOGS.md
  README.md
  docs/preview.png
  index.html
  package.json
  pnpm-lock.yaml
  public/preview.png
Labels: chore

#145 ci(build.yml): fix armv7 packages' architecture
  .github/workflows/build.yml
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
Labels: ci, not-yet-tested

#171 fix: time parsing is wrong
  package.json
  pnpm-lock.yaml
  src/utils/helper.ts
  src/utils/index.test.ts
  tsconfig.json
  vite.config.ts
Labels: fix, not-yet-tested

#170 docs(readme): add build-status badge
  README.md
Labels: documentation

#172 chore: run unite tests before commiting
  .husky/pre-commit
  package.json
Labels: chore

#175 ci(pr-build): add ready_for_review trigger
  .github/workflows/pr-build.yml
Labels: ci, not-yet-tested

#182 chore: update codeowners
  CODEOWNERS
Labels: chore

#180 ci(pr-build): ONLY keep arm64, amd64 as build targets
  .github/workflows/pr-build.yml
  install/friendly-filenames.json
Labels: ci, tested

#185 fix: avoid to install husky when not in a git repo
  Makefile
Labels: fix, not-yet-tested

#183 ci(pr-build): update trigger paths
  .github/workflows/build.yml
  .github/workflows/pr-build.yml
Labels: ci

#187 fix: reload icon not showing on small size screens
  .github/workflows/pr-build.yml
  src/App.tsx
  src/components/DraggableResourceBadge.tsx
  src/components/Header.tsx
  src/pages/Experiment.tsx
Labels: fix, not-yet-tested

#188 fix: rename modal not closing after changing rule names
  package.json
  pnpm-lock.yaml
  src/components/RenameFormModal.tsx
Labels: fix, not-yet-tested

#190 ci/fix(pr-build,build): fix submodule path trigger
  .github/workflows/build.yml
  .github/workflows/pr-build.yml
Labels: ci, fix, tested

#191 feat: add configure juicity modal
  src/components/ConfigureNodeFormModal/JuicityForm.tsx
  src/components/ConfigureNodeFormModal/index.tsx
  src/constants/default.ts
  src/constants/schema.ts
Labels: feature, not-yet-tested

#192 chore/feat: add checkout.sh
  hack/checkout.sh
Labels: chore, do-not-merge, feature

#193 ci/fix(generate-changelogs): fix dry_run input description
  .github/workflows/generate-changelogs.yml
Labels: ci, fix
