Repository daeuniverse/daed, pull requests merged in 2023-06, with the labels that each got.

#17 doc: update readme
  README.md
Labels: documentation

#32 ci(release-v0.1.0rc): add release changelogs
  CHANGELOGS.md
Labels: release

#36 docs: include a short notes for nightly builds
  docs/build.md
  docs/getting-started.md
Labels: documentation

#44 ci(sync): sync create pull request
  .github/workflows/sync-upstream-source.yml
Labels: ci

#46 ci(sync-upstream): general patches
  .github/workflows/sync-upstream-source.yml
Labels: ci

#48 fix(sync-upstream-docs): do not use ref in checkout action
  .github/workflows/sync-upstream-source.yml
Labels: ci

#35 ci: build-nightly workflow
  .github/workflows/build-nightly.yml
  .github/workflows/build.yml
  .github/workflows/develop-preview.yml
Labels: ci, do-not-merge

#50 docs(getting-started.md): correct a tiny typo
  docs/getting-started.md
Labels: documentation

#51 ci: ignore *.md to trigger build
  .github/workflows/build-nightly.yml
Labels: ci

#40 ci(build.yml): add Linux package hooks
  .github/workflows/build.yml
  .github/workflows/sync-upstream-source.yml
  install/package_after_install.sh
  install/package_after_remove.sh
  install/package_before_remove.sh
Labels: ci

#55 ci(build-nightly): demise develop branch trigger; use hotfix and test instead
  .github/workflows/build-nightly.yml
Labels: ci

#57 ci(build): fix missing dependant job
  .github/workflows/build.yml
Labels: ci

#66 chore(release-v0.1.0rc): update release changelogs
  CHANGELOGS.md
Labels: chore, release

#69 chore(issue-template): update default labels for bug-report
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/support-request.md
Labels: chore

#67 ci(build-nightly): add fetch-depth: 0
  .github/workflows/build-nightly.yml
Labels: ci

#71 feat: add description text for group policies
  src/components/ConfigFormModal.tsx
  src/components/GroupFormModal.tsx
  src/components/SelectItemWithDescription.tsx
  src/i18n/locales/en.json
  src/i18n/locales/zh-Hans.json
Labels: ci, feature

#72 feat(config): show interface ip addresses in interface select
  src/apis/query.ts
  src/components/ConfigFormModal.tsx
  src/schemas/gql/gql.ts
  src/schemas/gql/graphql.ts
Labels: feature

#73 fix(config): disable allow insecure by default
  src/constants/index.ts
Labels: fix

#70 feat: add loading state indicators
  src/components/FormActions.tsx
  src/components/Header.tsx
  src/components/ImportResourceFormModal.tsx
  src/pages/Orchestrate.tsx
Labels: feature

#75 ci(prerelease): include v*.*.*rc* (v0.1.1rc1) case
  .github/workflows/prerelease.yml
Labels: ci

#76 ci: add sync-upstream workflow
  .github/workflows/sync-upstream.yml
Labels: ci

#77 feat(group): show subscription tag on node hover
  src/components/SortableResourceBadge.tsx
  src/pages/Orchestrate.tsx
Labels: feature

#78 fix(subscription): loading indicator of update
  src/components/DraggableSubscriptionNodeBadge.tsx
  src/components/UpdateSubscriptionAction.tsx
  src/pages/Orchestrate.tsx
Labels: fix

#79 feat: drag nodes and subscriptions between groups
  src/components/DraggableResourceBadge.tsx
  src/components/DraggableResourceCard.tsx
  src/components/DraggableSubscriptionNodeBadge.tsx
  src/components/RenameFormModal.tsx
  src/components/SortableResourceBadge.tsx
  src/constants/index.ts
  src/pages/Experiment.tsx
  src/pages/Orchestrate.tsx
Labels: feature

#80 feat: restrict drag and drop area
  src/components/SelectItemWithDescription.tsx
  src/pages/Orchestrate.tsx
  src/utils/dnd-kit.ts
Labels: feature

#92 fix: default googledns add tcp
  src/constants/index.ts
Labels: fix

#91 fix: dragging not working properly
  src/pages/Orchestrate/Node.tsx
  src/pages/Orchestrate/Subscription.tsx
  src/pages/Orchestrate/index.tsx
Labels: fix

#96 fix(group): refresh after remove nodes/subs
  src/apis/mutation.ts
Labels: fix

#97 feat: add tooltip for header actions
  src/components/Header.tsx
  src/i18n/locales/en.json
  src/i18n/locales/zh-Hans.json
Labels: feature

#98 feat: show node protocol in card title
  src/components/DraggableResourceCard.tsx
  src/pages/Orchestrate/Node.tsx
Labels: feature

#100 feat: render qrcode in canvas to allow user to save image
  src/components/QRCodeModal.tsx
  src/components/UpdateSubscriptionAction.tsx
  src/pages/Orchestrate/Node.tsx
  src/pages/Orchestrate/Subscription.tsx
Labels: feature

#101 feat: use monaco editor for dns and routing
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/Header.tsx
  src/components/PlainTextFormModal.tsx
  src/constants/index.ts
  src/pages/Experiment.tsx
  src/schemas/gql/graphql.ts
  src/store/index.ts
Labels: feature

#102 feat: use theme `github` as default monaco editor light theme
  package.json
  pnpm-lock.yaml
  src/components/PlainTextFormModal.tsx
  src/constants/index.ts
  src/main.tsx
Labels: feature

#105 feat(editor): add routingA code highlight
  src/components/PlainTextFormModal.tsx
  src/main.tsx
Labels: feature

#106 feat(editor): render tags
  src/constants/index.ts
  src/main.tsx
Labels: feature

#108 feat: add header icon link to github project, and a footer
  src/components/Header.tsx
  src/pages/MainLayout.tsx
Labels: feature

#104 ci: introduce generate-changelogs workflow
  .github/workflows/generate-changelogs.yml
  .github/workflows/prerelease.yml
  package.json
Labels: ci

#109 feat: make plaintext modal fullscreen
  src/components/PlainTextFormModal.tsx
  src/constants/index.ts
Labels: feature

#110 feat: support small screen devices
  .prettierrc
  package.json
  pnpm-lock.yaml
  postcss.config.js
  src/App.tsx
  src/components/ConfigFormModal.tsx
  src/components/Header.tsx
  src/components/ImportResourceFormModal.tsx
  src/components/Table.tsx
  src/index.css
  src/pages/Home.tsx
  src/pages/MainLayout.tsx
  src/pages/Orchestrate/index.tsx
  tailwind.config.js
Labels: feature

#111 feat: responsive header
  src/components/ColorSchemeToggle.tsx
  src/components/Header.tsx
Labels: feature

#107 docs(readme): fix license badge issue and rework contributing section
  LICENSE
  LICENSE-MIT
  README.md
Labels: documentation

#113 feat: disable zooming and panning on mobile
  index.html
Labels: feature

#121 fix: footer is floating above modal overlay
  src/components/ConfigFormModal.tsx
  src/components/Header.tsx
  src/components/PlainTextFormModal.tsx
  src/pages/MainLayout.tsx
Labels: fix, not-yet-tested

#128 fix: import missing packages and clean up unreference files
  src/components/PlainTextFormModal.tsx
  src/constants/index.ts
  src/main.tsx
  src/pages/Experiment.tsx
Labels: fix
