Repository daeuniverse/daed, pull requests merged in 2023-09, with the labels that each got.

#248 ci(pick): fix build failure due to go mod not being updated
  .github/workflows/pick-build.yml
Labels: ci, not-yet-tested

#258 feat(routing): add dnsmasq to must_direct default routing
  src/constants/default.ts
Labels: feature, not-yet-tested

#251 feat(config): add form field `soMarkFromDae`
  package.json
  pnpm-lock.yaml
  src/apis/query.ts
  src/components/ConfigFormModal.tsx
  src/constants/default.ts
  src/i18n/locales/en.json
  src/i18n/locales/zh-Hans.json
  src/schemas/gql/gql.ts
  src/schemas/gql/graphql.ts
Labels: feature, not-yet-tested

#261 ci(generate-changelogs): update default assignees list
  .github/workflows/generate-changelogs.yml
Labels: ci
