Repository daeuniverse/daed, pull requests merged in 2023-08, with the labels that each got.

#206 chore(pr_template): fix typo
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#205 feat: set color scheme based on system preference
  src/App.tsx
Labels: feature, not-yet-tested

#208 feat: disable rollbackError, fixes #207
  src/apis/mutation.ts
Labels: feature, not-yet-tested

#217 fix: copy to clipboard not working when clipboard permissions not permitted
  package.json
  pnpm-lock.yaml
  src/components/QRCodeModal.tsx
Labels: fix, not-yet-tested

#218 feat: change editor font to `Source Code Pro`
  .npmrc
  README.md
  docs/preview.png
  docs/preview.webp
  index.html
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/logo.png
  public/logo.svg
  public/logo.webp
  public/site.webmanifest
  src/assets/logo.png
  src/assets/logo.svg
  src/components/Header.tsx
  src/constants/editor.ts
Labels: feature, not-yet-tested

#219 feat: add juicity pinned_certchain_sha256 config
  src/components/ConfigureNodeFormModal/JuicityForm.tsx
  src/constants/default.ts
  src/constants/schema.ts
  src/i18n/locales/en.json
  src/i18n/locales/zh-Hans.json
Labels: feature, not-yet-tested

#221 feat: add desktop file and icons
  install/daed.desktop
  install/icons/1024x1024.png
  install/icons/128x128.png
  install/icons/16x16.png
  install/icons/24x24.png
  install/icons/256x256.png
  install/icons/32x32.png
  install/icons/48x48.png
  install/icons/512x512.png
  install/icons/64x64.png
Labels: feature, not-yet-tested

#223 chore(pr_template): update section headers
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#227 chore: support build_mode=pie
  .github/workflows/build.yml
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
Labels: chore

#220 chore/refactor: rework issue_templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/proposal.yml
  .github/ISSUE_TEMPLATE/support-request.md
  .github/ISSUE_TEMPLATE/support-request.yml
Labels: chore, refactor

#229 ci: add pick-build workflow
  .github/workflows/pick-build.yml
  Makefile
Labels: ci, not-yet-tested

#231 ci(pick): fix build error when daed is not main
  .github/workflows/pick-build.yml
Labels: ci, tested, not-yet-tested

#234 chore: remove BUILD_ARGS in workflows
  .github/workflows/build.yml
  .github/workflows/pick-build.yml
  .github/workflows/prerelease.yml
  .github/workflows/release.yml
Labels: chore

#246 docs: Added Debian, RedHat, openSUSE, installation instructions
  docs/getting-started.md
Labels: documentation

#247 docs(getting-started): make subtle changes
  docs/getting-started.md
Labels: documentation
