Repository daeuniverse/daed, pull requests merged in 2024-06, with the labels that each got.

#432 ci: update ci modules to the latest version
  .github/workflows/build.yml
  .github/workflows/generate-changelogs.yml
  .github/workflows/pick-build.yml
  .github/workflows/pr-build.yml
  .github/workflows/prerelease.yml
  .github/workflows/publish-docker-image.yml
  .github/workflows/publish-gh-pages.yml
  .github/workflows/release.yml
  .vscode/settings.json
Labels: ci, tested

#441 ci/feat: support customized git remote for Pick Build
  .github/workflows/pick-build.yml
Labels: ci, feature, tested

#440 feat: add configure hysteria2 modal
  src/components/ConfigureNodeFormModal/Hysteria2Form.tsx
  src/components/ConfigureNodeFormModal/index.tsx
  src/constants/default.ts
  src/constants/schema.ts
  src/i18n/locales/en.json
  src/i18n/locales/zh-Hans.json
  src/utils/node.ts
Labels: feature, not-yet-tested

#444 ci(release): draft release v0.7.0rc1
  CHANGELOGS.md
Labels: ci, not-yet-tested

#445 ci(docker): update go version to 1.22
  publish.Dockerfile
Labels: ci, not-yet-tested

#446 ci(release): draft release v0.7.0rc1.1
  CHANGELOGS.md
Labels: ci, not-yet-tested
